// Copyright (c) 2026 Torlando Tech LLC.
//
// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//
//  LXStamper.swift
//  LXMFSwift
//
//  Proof-of-work stamp generation and validation for LXMF.
//  Matches Python LXMF LXStamper.py exactly for interoperability.
//
//  Stamps are hashcash-style proof-of-work used for spam prevention.
//  Recipients can require senders to generate stamps before accepting messages.
//
//  Reference: LXMF/LXStamper.py
//

import Foundation
import CryptoKit
import ReticulumSwift

/// Proof-of-work stamp generator and validator.
///
/// Stamps are generated by finding a 32-byte nonce such that
/// SHA256(workblock + stamp) has at least N leading zero bits,
/// where N is the "cost" of the stamp.
///
/// The workblock is derived from the message ID using HKDF expansion
/// over 3000 rounds x 256 bytes = 768KB total.
///
/// Example:
/// ```swift
/// // Generate stamp for message
/// let (stamp, rounds) = await LXStamper.generateStamp(messageID: msgID, cost: 16)
///
/// // Validate received stamp
/// let workblock = LXStamper.stampWorkblock(material: msgID)
/// let isValid = LXStamper.stampValid(stamp: stamp, cost: 16, workblock: workblock)
/// ```
public enum LXStamper {

    // MARK: - Constants

    /// Number of HKDF expansion rounds for workblock generation
    /// Python: WORKBLOCK_EXPAND_ROUNDS = 3000
    public static let EXPAND_ROUNDS = 3000

    /// Number of HKDF expansion rounds for propagation node stamp validation
    /// Python: WORKBLOCK_EXPAND_ROUNDS_PN = 1000
    public static let EXPAND_ROUNDS_PN = 1000

    /// Bytes per expansion round
    /// Python: each round generates 256 bytes
    public static let EXPAND_LENGTH = 256

    /// Default stamp cost (leading zero bits required)
    /// Python: DEFAULT_COST = 16
    public static let DEFAULT_COST = 16

    /// Special cost value for ticket validation
    /// Python: COST_TICKET = 0x100 = 256
    public static let COST_TICKET = 0x100

    /// Stamp size in bytes (32 bytes = 256 bits)
    /// Python: STAMP_SIZE = 256//8 = 32
    public static let STAMP_SIZE = 32

    // MARK: - Workblock Generation

    /// Generate workblock from material using HKDF expansion.
    ///
    /// Matches Python LXStamper.py lines 28-39:
    /// ```python
    /// def stamp_workblock(material, expand_rounds=WORKBLOCK_EXPAND_ROUNDS):
    ///     workblock = b""
    ///     for n in range(expand_rounds):
    ///         workblock += RNS.Cryptography.hkdf(length=256,
    ///                                            derive_from=material,
    ///                                            salt=RNS.Identity.full_hash(material+msgpack.packb(n)),
    ///                                            context=None)
    ///     return workblock
    /// ```
    ///
    /// - Parameters:
    ///   - material: Input material (typically message ID / transient ID)
    ///   - expandRounds: Number of HKDF expansion rounds (default: 3000, PN: 1000)
    /// - Returns: Workblock of size expandRounds x 256 bytes
    public static func stampWorkblock(material: Data, expandRounds: Int = EXPAND_ROUNDS) -> Data {
        var workblock = Data()
        workblock.reserveCapacity(expandRounds * EXPAND_LENGTH)

        for n in 0..<expandRounds {
            // msgpack.packb(n) - pack counter as MessagePack integer
            let counter = packMessagePackInt(n)

            // salt = SHA256(material + counter)
            let saltInput = material + counter
            let salt = SHA256.hash(data: saltInput)

            // HKDF expand with material as IKM, computed salt, no context
            let expanded = KeyDerivation.deriveKey(
                length: EXPAND_LENGTH,
                inputKeyMaterial: material,
                salt: Data(salt),
                context: nil
            )

            workblock.append(expanded)
        }

        return workblock
    }

    // MARK: - Stamp Validation

    /// Check if stamp is valid for given cost and workblock.
    ///
    /// Matches Python LXStamper.py lines 52-56:
    /// ```python
    /// def stamp_valid(stamp, target_cost, workblock):
    ///     target = 0b1 << 256-target_cost
    ///     result = RNS.Identity.full_hash(workblock+stamp)
    ///     if int.from_bytes(result, byteorder="big") > target: return False
    ///     else: return True
    /// ```
    ///
    /// - Parameters:
    ///   - stamp: The 32-byte proof-of-work stamp
    ///   - cost: Required number of leading zero bits
    ///   - workblock: The workblock generated from message ID
    /// - Returns: True if stamp meets the cost requirement
    public static func stampValid(stamp: Data, cost: Int, workblock: Data) -> Bool {
        // Compute hash of workblock + stamp
        let material = workblock + stamp
        let hash = SHA256.hash(data: material)
        let hashData = Data(hash)

        // Compare hash against target
        // target = 1 << (256 - cost)
        // This means the hash must have at least 'cost' leading zero bits
        return countLeadingZeroBits(hashData) >= cost
    }

    // MARK: - Stamp Generation

    /// Generate proof-of-work stamp asynchronously.
    ///
    /// Matches Python LXStamper.py lines 100-122.
    /// Generates workblock, then tries random 32-byte stamps until one passes validation.
    ///
    /// - Parameters:
    ///   - messageID: Message identifier to generate stamp for
    ///   - cost: Required number of leading zero bits (default: 16)
    ///   - expandRounds: Number of HKDF expansion rounds (default: 3000, PN: 1000)
    /// - Returns: Tuple of (stamp, rounds) where rounds is number of attempts
    public static func generateStamp(messageID: Data, cost: Int = DEFAULT_COST, expandRounds: Int = EXPAND_ROUNDS) async -> (stamp: Data, rounds: Int) {
        // Mirror python `job_linux`'s parallel design — race N workers,
        // first to find a valid stamp wins. See port-deviations.md for the
        // full justification + python ref site. Existing single-threaded
        // callers (tests, conformance bridge) can still call
        // `generateStampSync` directly for deterministic single-CPU runs.
        let workblock = stampWorkblock(material: messageID, expandRounds: expandRounds)
        return await generateStampParallel(workblock: workblock, cost: cost)
    }

    /// Synchronous stamp generation (for internal use and testing).
    ///
    /// Matches Python job_simple() in LXStamper.py lines 156-188:
    /// ```python
    /// while not sv(pstamp, stamp_cost, workblock):
    ///     pstamp = os.urandom(256//8); rounds += 1
    /// ```
    ///
    /// Performance: pre-feeds the (large) workblock into a SHA256 context
    /// once, then per attempt only digests the 32-byte stamp on a copy.
    /// Avoids the per-attempt 256KB allocation + redundant SHA over the
    /// workblock that a naive `SHA256.hash(workblock + stamp)` loop does.
    /// Mirrors the kotlin port's reticulum-kt#66 fix (which dropped cost=16
    /// stamp gen from ~21s to ~400ms on phones); identical hash output.
    ///
    /// - Parameters:
    ///   - workblock: Pre-computed workblock
    ///   - cost: Required number of leading zero bits
    /// - Returns: Tuple of (stamp, rounds)
    public static func generateStampSync(workblock: Data, cost: Int) -> (stamp: Data, rounds: Int) {
        var rounds = 0
        var stamp = Data(count: STAMP_SIZE)

        // Pre-fed digest: workblock is hashed exactly once. Each attempt
        // copies the in-progress digest state, finalises with the stamp,
        // and reads the 32-byte hash. This is byte-for-byte identical to
        // SHA256.hash(workblock + stamp) but ~Nx faster (N = workblock
        // size in bytes / stamp size, ~8000x at cost=16 PN workblock).
        let primed = SHA256_PrimedDigest(prefix: workblock)

        repeat {
            // Generate random 32-byte stamp candidate
            stamp.withUnsafeMutableBytes { buf in
                _ = SecRandomCopyBytes(kSecRandomDefault, STAMP_SIZE, buf.baseAddress!)
            }
            rounds += 1

            // Finalize a copy of the primed digest with the stamp suffix.
            let hash = primed.finalize(suffix: stamp)
            if countLeadingZeroBits(hash) >= cost {
                return (stamp, rounds)
            }
        } while true
    }

    /// Concurrent stamp generation: spawns N CPU workers that each run the
    /// inner loop on its own SecureRandom + primed digest, racing to find
    /// a valid stamp. First worker to find one wins; others see the result
    /// pointer flip and exit. Mirrors the kotlin port's parallel job design.
    ///
    /// Use this from `generateStamp(messageID:cost:expandRounds:)` instead
    /// of the single-threaded `generateStampSync`. Provided as a separate
    /// helper so existing callers (tests + bridges) that prefer the
    /// deterministic single-threaded path keep working.
    public static func generateStampParallel(workblock: Data, cost: Int) async -> (stamp: Data, rounds: Int) {
        let workerCount = max(1, min(8, ProcessInfo.processInfo.activeProcessorCount))
        // Shared "found" container — first worker to win sets it.
        let found = StampResultBox()

        return await withTaskGroup(of: Int.self) { group in
            for _ in 0..<workerCount {
                group.addTask(priority: .userInitiated) {
                    var localRounds = 0
                    var stamp = Data(count: STAMP_SIZE)
                    let primed = SHA256_PrimedDigest(prefix: workblock)

                    while !found.isSet() {
                        stamp.withUnsafeMutableBytes { buf in
                            _ = SecRandomCopyBytes(kSecRandomDefault, STAMP_SIZE, buf.baseAddress!)
                        }
                        localRounds += 1
                        let hash = primed.finalize(suffix: stamp)
                        if countLeadingZeroBits(hash) >= cost {
                            found.set(stamp: stamp)
                            return localRounds
                        }
                    }
                    return localRounds
                }
            }
            var totalRounds = 0
            for await r in group { totalRounds += r }
            // `found` is guaranteed non-nil here: the first winner triggers
            // every other worker's `found.isSet()` check and they exit, but
            // none of them complete before the group has at least one
            // value. If this ever returns nil, that's a logic bug.
            return (found.stamp ?? Data(count: STAMP_SIZE), totalRounds)
        }
    }

    // MARK: - Stamp Value

    /// Calculate the achieved stamp value (number of leading zero bits).
    ///
    /// Matches Python LXStamper.py lines 41-50:
    /// ```python
    /// def stamp_value(workblock, stamp):
    ///     value = 0
    ///     bits = 256
    ///     material = RNS.Identity.full_hash(workblock+stamp)
    ///     i = int.from_bytes(material, byteorder="big")
    ///     while ((i & (1 << (bits - 1))) == 0):
    ///         i = (i << 1)
    ///         value += 1
    ///     return value
    /// ```
    ///
    /// - Parameters:
    ///   - workblock: The workblock
    ///   - stamp: The stamp to evaluate
    /// - Returns: Number of leading zero bits in hash
    public static func stampValue(workblock: Data, stamp: Data) -> Int {
        let material = workblock + stamp
        let hash = SHA256.hash(data: material)
        let hashData = Data(hash)

        return countLeadingZeroBits(hashData)
    }

    // MARK: - Helper Functions

    /// Count leading zero bits in data.
    ///
    /// This implements the Python algorithm:
    /// ```python
    /// while ((i & (1 << (bits - 1))) == 0):
    ///     i = (i << 1)
    ///     value += 1
    /// ```
    ///
    /// - Parameter data: Byte data to analyze
    /// - Returns: Number of leading zero bits
    private static func countLeadingZeroBits(_ data: Data) -> Int {
        var count = 0

        for byte in data {
            if byte == 0 {
                // All 8 bits are zero
                count += 8
            } else {
                // Count leading zeros in this byte
                count += byte.leadingZeroBitCount
                break
            }
        }

        return count
    }

    /// Pre-fed SHA256 digest helper. Wraps CryptoKit's `SHA256` so the
    /// inner stamp loop can hash `workblock + stamp` without re-allocating
    /// the (large) workblock prefix on every attempt. See
    /// `port-deviations.md` for the python-ref justification.
    ///
    /// CryptoKit's `Hasher` value type COWs internally on `update()`; we
    /// rely on that — `finalize(suffix:)` makes a fresh local copy of the
    /// primed hasher, calls `update()` with the 32-byte stamp, finalizes,
    /// and returns the digest. The original `primed` is unchanged so the
    /// next call starts from the same workblock-prefilled state.
    private struct SHA256_PrimedDigest {
        private let primed: SHA256

        init(prefix: Data) {
            var h = SHA256()
            h.update(data: prefix)
            self.primed = h
        }

        func finalize(suffix: Data) -> Data {
            var h = primed
            h.update(data: suffix)
            return Data(h.finalize())
        }
    }

    /// Worker-shared "first valid stamp wins" container for
    /// `generateStampParallel`. Mirrors python `job_linux`'s
    /// `stop_event + result_queue` pair. See `port-deviations.md`.
    private final class StampResultBox: @unchecked Sendable {
        private let lock = NSLock()
        private var _stamp: Data?

        var stamp: Data? {
            lock.lock(); defer { lock.unlock() }
            return _stamp
        }

        func isSet() -> Bool {
            lock.lock(); defer { lock.unlock() }
            return _stamp != nil
        }

        func set(stamp: Data) {
            lock.lock(); defer { lock.unlock() }
            if _stamp == nil { _stamp = stamp }
        }
    }

    /// Pack integer as MessagePack format.
    ///
    /// Matches Python msgpack.packb(n) for small integers.
    /// MessagePack positive fixint: 0x00-0x7f for values 0-127
    /// MessagePack uint 8: 0xcc + 1 byte for values 128-255
    /// MessagePack uint 16: 0xcd + 2 bytes for values 256-65535
    /// MessagePack uint 32: 0xce + 4 bytes for larger values
    ///
    /// - Parameter value: Integer to pack
    /// - Returns: MessagePack encoded data
    private static func packMessagePackInt(_ value: Int) -> Data {
        if value >= 0 && value <= 0x7f {
            // Positive fixint
            return Data([UInt8(value)])
        } else if value >= 0 && value <= Int(UInt8.max) {
            // uint 8
            return Data([0xcc, UInt8(value)])
        } else if value >= 0 && value <= Int(UInt16.max) {
            // uint 16
            var v = UInt16(value).bigEndian
            var data = Data([0xcd])
            withUnsafeBytes(of: &v) { data.append(contentsOf: $0) }
            return data
        } else {
            // uint 32
            var v = UInt32(value).bigEndian
            var data = Data([0xce])
            withUnsafeBytes(of: &v) { data.append(contentsOf: $0) }
            return data
        }
    }
}
