//
//  LXStamper.swift
//  LXMFSwift
//
//  Proof-of-work stamp generation and validation for LXMF.
//  Matches Python LXMF LXStamper.py exactly for interoperability.
//
//  Stamps are hashcash-style proof-of-work used for spam prevention.
//  Recipients can require senders to generate stamps before accepting messages.
//
//  Reference: LXMF/LXStamper.py
//

import Foundation
import CryptoKit
import ReticulumSwift

/// Proof-of-work stamp generator and validator.
///
/// Stamps are generated by finding a 32-byte nonce such that
/// SHA256(workblock + stamp) has at least N leading zero bits,
/// where N is the "cost" of the stamp.
///
/// The workblock is derived from the message ID using HKDF expansion
/// over 3000 rounds x 256 bytes = 768KB total.
///
/// Example:
/// ```swift
/// // Generate stamp for message
/// let (stamp, rounds) = await LXStamper.generateStamp(messageID: msgID, cost: 16)
///
/// // Validate received stamp
/// let workblock = LXStamper.stampWorkblock(material: msgID)
/// let isValid = LXStamper.stampValid(stamp: stamp, cost: 16, workblock: workblock)
/// ```
public enum LXStamper {

    // MARK: - Constants

    /// Number of HKDF expansion rounds for workblock generation
    /// Python: WORKBLOCK_EXPAND_ROUNDS = 3000
    public static let EXPAND_ROUNDS = 3000

    /// Bytes per expansion round
    /// Python: each round generates 256 bytes
    public static let EXPAND_LENGTH = 256

    /// Default stamp cost (leading zero bits required)
    /// Python: DEFAULT_COST = 16
    public static let DEFAULT_COST = 16

    /// Special cost value for ticket validation
    /// Python: COST_TICKET = 0x100 = 256
    public static let COST_TICKET = 0x100

    /// Stamp size in bytes (32 bytes = 256 bits)
    /// Python: STAMP_SIZE = 256//8 = 32
    public static let STAMP_SIZE = 32

    // MARK: - Workblock Generation

    /// Generate workblock from material using HKDF expansion.
    ///
    /// Matches Python LXStamper.py lines 28-39:
    /// ```python
    /// def stamp_workblock(material, expand_rounds=WORKBLOCK_EXPAND_ROUNDS):
    ///     workblock = b""
    ///     for n in range(expand_rounds):
    ///         workblock += RNS.Cryptography.hkdf(length=256,
    ///                                            derive_from=material,
    ///                                            salt=RNS.Identity.full_hash(material+msgpack.packb(n)),
    ///                                            context=None)
    ///     return workblock
    /// ```
    ///
    /// - Parameter material: Input material (typically message ID)
    /// - Returns: 768000-byte workblock (3000 x 256)
    public static func stampWorkblock(material: Data) -> Data {
        var workblock = Data()
        workblock.reserveCapacity(EXPAND_ROUNDS * EXPAND_LENGTH)

        for n in 0..<EXPAND_ROUNDS {
            // msgpack.packb(n) - pack counter as MessagePack integer
            let counter = packMessagePackInt(n)

            // salt = SHA256(material + counter)
            let saltInput = material + counter
            let salt = SHA256.hash(data: saltInput)

            // HKDF expand with material as IKM, computed salt, no context
            let expanded = KeyDerivation.deriveKey(
                length: EXPAND_LENGTH,
                inputKeyMaterial: material,
                salt: Data(salt),
                context: nil
            )

            workblock.append(expanded)
        }

        return workblock
    }

    // MARK: - Stamp Validation

    /// Check if stamp is valid for given cost and workblock.
    ///
    /// Matches Python LXStamper.py lines 52-56:
    /// ```python
    /// def stamp_valid(stamp, target_cost, workblock):
    ///     target = 0b1 << 256-target_cost
    ///     result = RNS.Identity.full_hash(workblock+stamp)
    ///     if int.from_bytes(result, byteorder="big") > target: return False
    ///     else: return True
    /// ```
    ///
    /// - Parameters:
    ///   - stamp: The 32-byte proof-of-work stamp
    ///   - cost: Required number of leading zero bits
    ///   - workblock: The workblock generated from message ID
    /// - Returns: True if stamp meets the cost requirement
    public static func stampValid(stamp: Data, cost: Int, workblock: Data) -> Bool {
        // Compute hash of workblock + stamp
        let material = workblock + stamp
        let hash = SHA256.hash(data: material)
        let hashData = Data(hash)

        // Compare hash against target
        // target = 1 << (256 - cost)
        // This means the hash must have at least 'cost' leading zero bits
        return countLeadingZeroBits(hashData) >= cost
    }

    // MARK: - Stamp Generation

    /// Generate proof-of-work stamp asynchronously.
    ///
    /// Matches Python LXStamper.py lines 100-122.
    /// Generates workblock, then tries random 32-byte stamps until one passes validation.
    ///
    /// - Parameters:
    ///   - messageID: Message identifier to generate stamp for
    ///   - cost: Required number of leading zero bits (default: 16)
    /// - Returns: Tuple of (stamp, rounds) where rounds is number of attempts
    public static func generateStamp(messageID: Data, cost: Int = DEFAULT_COST) async -> (stamp: Data, rounds: Int) {
        // Use Task.detached to run on background thread and avoid blocking
        return await Task.detached(priority: .userInitiated) {
            let workblock = stampWorkblock(material: messageID)
            return generateStampSync(workblock: workblock, cost: cost)
        }.value
    }

    /// Synchronous stamp generation (for internal use and testing).
    ///
    /// Matches Python job_simple() in LXStamper.py lines 156-188:
    /// ```python
    /// while not sv(pstamp, stamp_cost, workblock):
    ///     pstamp = os.urandom(256//8); rounds += 1
    /// ```
    ///
    /// - Parameters:
    ///   - workblock: Pre-computed workblock
    ///   - cost: Required number of leading zero bits
    /// - Returns: Tuple of (stamp, rounds)
    public static func generateStampSync(workblock: Data, cost: Int) -> (stamp: Data, rounds: Int) {
        var rounds = 0
        var stamp: Data

        repeat {
            // Generate random 32-byte stamp candidate
            stamp = Data((0..<STAMP_SIZE).map { _ in UInt8.random(in: 0...255) })
            rounds += 1
        } while !stampValid(stamp: stamp, cost: cost, workblock: workblock)

        return (stamp, rounds)
    }

    // MARK: - Stamp Value

    /// Calculate the achieved stamp value (number of leading zero bits).
    ///
    /// Matches Python LXStamper.py lines 41-50:
    /// ```python
    /// def stamp_value(workblock, stamp):
    ///     value = 0
    ///     bits = 256
    ///     material = RNS.Identity.full_hash(workblock+stamp)
    ///     i = int.from_bytes(material, byteorder="big")
    ///     while ((i & (1 << (bits - 1))) == 0):
    ///         i = (i << 1)
    ///         value += 1
    ///     return value
    /// ```
    ///
    /// - Parameters:
    ///   - workblock: The workblock
    ///   - stamp: The stamp to evaluate
    /// - Returns: Number of leading zero bits in hash
    public static func stampValue(workblock: Data, stamp: Data) -> Int {
        let material = workblock + stamp
        let hash = SHA256.hash(data: material)
        let hashData = Data(hash)

        return countLeadingZeroBits(hashData)
    }

    // MARK: - Helper Functions

    /// Count leading zero bits in data.
    ///
    /// This implements the Python algorithm:
    /// ```python
    /// while ((i & (1 << (bits - 1))) == 0):
    ///     i = (i << 1)
    ///     value += 1
    /// ```
    ///
    /// - Parameter data: Byte data to analyze
    /// - Returns: Number of leading zero bits
    private static func countLeadingZeroBits(_ data: Data) -> Int {
        var count = 0

        for byte in data {
            if byte == 0 {
                // All 8 bits are zero
                count += 8
            } else {
                // Count leading zeros in this byte
                count += byte.leadingZeroBitCount
                break
            }
        }

        return count
    }

    /// Pack integer as MessagePack format.
    ///
    /// Matches Python msgpack.packb(n) for small integers.
    /// MessagePack positive fixint: 0x00-0x7f for values 0-127
    /// MessagePack uint 8: 0xcc + 1 byte for values 128-255
    /// MessagePack uint 16: 0xcd + 2 bytes for values 256-65535
    /// MessagePack uint 32: 0xce + 4 bytes for larger values
    ///
    /// - Parameter value: Integer to pack
    /// - Returns: MessagePack encoded data
    private static func packMessagePackInt(_ value: Int) -> Data {
        if value >= 0 && value <= 0x7f {
            // Positive fixint
            return Data([UInt8(value)])
        } else if value >= 0 && value <= Int(UInt8.max) {
            // uint 8
            return Data([0xcc, UInt8(value)])
        } else if value >= 0 && value <= Int(UInt16.max) {
            // uint 16
            var v = UInt16(value).bigEndian
            var data = Data([0xcd])
            withUnsafeBytes(of: &v) { data.append(contentsOf: $0) }
            return data
        } else {
            // uint 32
            var v = UInt32(value).bigEndian
            var data = Data([0xce])
            withUnsafeBytes(of: &v) { data.append(contentsOf: $0) }
            return data
        }
    }
}
