//
//  TelemetryTests.swift
//  LXMFSwiftTests
//
//  Interop tests for Sideband-compatible telemetry encoding/decoding.
//  Test vectors generated by Python Sideband telemeter code using umsgpack.
//

import XCTest
@testable import LXMFSwift

final class TelemetryTests: XCTestCase {

    // MARK: - Test Vectors (generated by Python)

    // Python: struct.pack("!i", 37774900)
    private let sanFranciscoLatBytes = Data([0x02, 0x40, 0x66, 0x34])
    // Python: struct.pack("!i", -122419400)
    private let sanFranciscoLonBytes = Data([0xf8, 0xb4, 0x07, 0x38])
    // Python: struct.pack("!i", 10000)  -- 100.0 * 100
    private let altitudeBytes = Data([0x00, 0x00, 0x27, 0x10])
    // Python: struct.pack("!I", 550)  -- 5.5 * 100
    private let speedBytes = Data([0x00, 0x00, 0x02, 0x26])
    // Python: struct.pack("!i", 18000)  -- 180.0 * 100
    private let bearingBytes = Data([0x00, 0x00, 0x46, 0x50])
    // Python: struct.pack("!H", 1000)  -- 10.0 * 100
    private let accuracyBytes = Data([0x03, 0xe8])

    /// Full msgpack-encoded telemetry from Python:
    /// {SID_TIME: 1703980800, SID_LOCATION: [lat, lon, alt, spd, brg, acc, ts]}
    private let pythonPackedHex = "8201ce6590af000297c40402406634c404f8b40738c40400002710c40400000226c40400004650c40203e8ce6590af00"

    /// Cease signal: all zeros
    private let pythonCeaseHex = "8201000297c40400000000c40400000000c40400000000c40400000000c40400000000c402000000"

    /// Sydney, Australia: lat=-33.8688, lon=151.2093
    private let pythonSydneyHex = "8201ce6590af640297c404fdfb3400c40409034554c404000016a8c40400000000c40400000000c40205dcce6590af64"

    // MARK: - LocationTelemetry Binary Encoding Tests

    func testLocationTelemetryPacksLatitudeCorrectly() {
        let loc = LocationTelemetry(
            latitude: 37.7749, longitude: -122.4194, altitude: 100.0,
            speed: 5.5, bearing: 180.0, accuracy: 10.0, lastUpdate: 1703980800
        )
        let array = loc.toSensorArray()

        // Index 0: latitude
        guard case .binary(let latData) = array[0] else {
            XCTFail("Expected binary for latitude"); return
        }
        XCTAssertEqual(latData, sanFranciscoLatBytes, "Latitude bytes mismatch")
    }

    func testLocationTelemetryPacksLongitudeCorrectly() {
        let loc = LocationTelemetry(
            latitude: 37.7749, longitude: -122.4194, altitude: 100.0,
            speed: 5.5, bearing: 180.0, accuracy: 10.0, lastUpdate: 1703980800
        )
        let array = loc.toSensorArray()

        guard case .binary(let lonData) = array[1] else {
            XCTFail("Expected binary for longitude"); return
        }
        XCTAssertEqual(lonData, sanFranciscoLonBytes, "Longitude bytes mismatch (negative value)")
    }

    func testLocationTelemetryPacksAllFieldsCorrectly() {
        let loc = LocationTelemetry(
            latitude: 37.7749, longitude: -122.4194, altitude: 100.0,
            speed: 5.5, bearing: 180.0, accuracy: 10.0, lastUpdate: 1703980800
        )
        let array = loc.toSensorArray()

        XCTAssertEqual(array.count, 7, "Sensor array must have exactly 7 elements")

        // Verify each binary field
        if case .binary(let altData) = array[2] { XCTAssertEqual(altData, altitudeBytes) }
        else { XCTFail("Expected binary for altitude") }

        if case .binary(let spdData) = array[3] { XCTAssertEqual(spdData, speedBytes) }
        else { XCTFail("Expected binary for speed") }

        if case .binary(let brgData) = array[4] { XCTAssertEqual(brgData, bearingBytes) }
        else { XCTFail("Expected binary for bearing") }

        if case .binary(let accData) = array[5] { XCTAssertEqual(accData, accuracyBytes) }
        else { XCTFail("Expected binary for accuracy") }

        // Index 6: timestamp as integer
        if case .int(let ts) = array[6] { XCTAssertEqual(ts, 1703980800) }
        else { XCTFail("Expected int for timestamp") }
    }

    // MARK: - Round-Trip Tests

    func testLocationTelemetryRoundTrip() {
        let original = LocationTelemetry(
            latitude: 37.7749, longitude: -122.4194, altitude: 100.0,
            speed: 5.5, bearing: 180.0, accuracy: 10.0, lastUpdate: 1703980800
        )

        let array = original.toSensorArray()
        let decoded = LocationTelemetry.fromSensorArray(array)

        XCTAssertNotNil(decoded)
        XCTAssertEqual(decoded!.latitude, 37.7749, accuracy: 0.000001)
        XCTAssertEqual(decoded!.longitude, -122.4194, accuracy: 0.000001)
        XCTAssertEqual(decoded!.altitude, 100.0, accuracy: 0.01)
        XCTAssertEqual(decoded!.speed, 5.5, accuracy: 0.01)
        XCTAssertEqual(decoded!.bearing, 180.0, accuracy: 0.01)
        XCTAssertEqual(decoded!.accuracy, 10.0, accuracy: 0.01)
        XCTAssertEqual(decoded!.lastUpdate, 1703980800)
    }

    func testNegativeLatitudeRoundTrip() {
        // Sydney, Australia
        let original = LocationTelemetry(
            latitude: -33.8688, longitude: 151.2093, altitude: 58.0,
            speed: 0.0, bearing: 0.0, accuracy: 15.0, lastUpdate: 1703980900
        )

        let array = original.toSensorArray()
        let decoded = LocationTelemetry.fromSensorArray(array)

        XCTAssertNotNil(decoded)
        XCTAssertEqual(decoded!.latitude, -33.8688, accuracy: 0.000001)
        XCTAssertEqual(decoded!.longitude, 151.2093, accuracy: 0.000001)
        XCTAssertEqual(decoded!.altitude, 58.0, accuracy: 0.01)
    }

    // MARK: - TelemetryPacket Encode/Decode Tests

    func testTelemetryPacketEncodeMatchesPython() {
        let loc = LocationTelemetry(
            latitude: 37.7749, longitude: -122.4194, altitude: 100.0,
            speed: 5.5, bearing: 180.0, accuracy: 10.0, lastUpdate: 1703980800
        )
        let packet = TelemetryPacket(timestamp: 1703980800, location: loc)
        let encoded = packet.encode()

        let expectedBytes = Data(hexString: pythonPackedHex)!
        XCTAssertEqual(encoded, expectedBytes,
                       "Encoded telemetry must match Python umsgpack output byte-for-byte.\n" +
                       "Swift:  \(encoded.map { String(format: "%02x", $0) }.joined())\n" +
                       "Python: \(pythonPackedHex)")
    }

    func testTelemetryPacketDecodePythonBytes() {
        let pythonBytes = Data(hexString: pythonPackedHex)!
        let packet = TelemetryPacket.decode(from: pythonBytes)

        XCTAssertNotNil(packet, "Failed to decode Python-generated telemetry bytes")
        XCTAssertEqual(packet!.timestamp, 1703980800)
        XCTAssertNotNil(packet!.location)

        let loc = packet!.location!
        XCTAssertEqual(loc.latitude, 37.7749, accuracy: 0.000001)
        XCTAssertEqual(loc.longitude, -122.4194, accuracy: 0.000001)
        XCTAssertEqual(loc.altitude, 100.0, accuracy: 0.01)
        XCTAssertEqual(loc.speed, 5.5, accuracy: 0.01)
        XCTAssertEqual(loc.bearing, 180.0, accuracy: 0.01)
        XCTAssertEqual(loc.accuracy, 10.0, accuracy: 0.01)
        XCTAssertEqual(loc.lastUpdate, 1703980800)
    }

    func testCeaseSignalMatchesPython() {
        let cease = LocationTelemetry.ceaseSignal()
        let packet = TelemetryPacket(timestamp: 0, location: cease)
        let encoded = packet.encode()

        let expectedBytes = Data(hexString: pythonCeaseHex)!
        XCTAssertEqual(encoded, expectedBytes,
                       "Cease signal must match Python output.\n" +
                       "Swift:  \(encoded.map { String(format: "%02x", $0) }.joined())\n" +
                       "Python: \(pythonCeaseHex)")
    }

    func testCeaseSignalDetection() {
        let pythonBytes = Data(hexString: pythonCeaseHex)!
        let packet = TelemetryPacket.decode(from: pythonBytes)

        XCTAssertNotNil(packet)
        XCTAssertNotNil(packet!.location)
        XCTAssertTrue(packet!.location!.isCeased, "All-zero location should be detected as cease signal")
    }

    func testSydneyNegativeLatitudeMatchesPython() {
        let loc = LocationTelemetry(
            latitude: -33.8688, longitude: 151.2093, altitude: 58.0,
            speed: 0.0, bearing: 0.0, accuracy: 15.0, lastUpdate: 1703980900
        )
        let packet = TelemetryPacket(timestamp: 1703980900, location: loc)
        let encoded = packet.encode()

        let expectedBytes = Data(hexString: pythonSydneyHex)!
        XCTAssertEqual(encoded, expectedBytes,
                       "Sydney telemetry must match Python output (negative latitude).\n" +
                       "Swift:  \(encoded.map { String(format: "%02x", $0) }.joined())\n" +
                       "Python: \(pythonSydneyHex)")
    }

    func testDecodeSydneyFromPython() {
        let pythonBytes = Data(hexString: pythonSydneyHex)!
        let packet = TelemetryPacket.decode(from: pythonBytes)

        XCTAssertNotNil(packet)
        let loc = packet!.location!
        XCTAssertEqual(loc.latitude, -33.8688, accuracy: 0.000001)
        XCTAssertEqual(loc.longitude, 151.2093, accuracy: 0.000001)
        XCTAssertEqual(loc.altitude, 58.0, accuracy: 0.01)
        XCTAssertEqual(loc.speed, 0.0, accuracy: 0.01)
        XCTAssertEqual(loc.accuracy, 15.0, accuracy: 0.01)
    }

    // MARK: - TelemetryPacket Full Round-Trip

    func testEncodeDecodeRoundTrip() {
        let original = LocationTelemetry(
            latitude: -45.031162, longitude: 168.662643, altitude: 310.5,
            speed: 12.34, bearing: 275.0, accuracy: 8.5, lastUpdate: 1703980999
        )
        let packet = TelemetryPacket(timestamp: 1703980999, location: original)

        let encoded = packet.encode()
        let decoded = TelemetryPacket.decode(from: encoded)

        XCTAssertNotNil(decoded)
        XCTAssertEqual(decoded!.timestamp, 1703980999)

        let loc = decoded!.location!
        XCTAssertEqual(loc.latitude, -45.031162, accuracy: 0.000001)
        XCTAssertEqual(loc.longitude, 168.662643, accuracy: 0.000001)
        XCTAssertEqual(loc.altitude, 310.5, accuracy: 0.01)
        XCTAssertEqual(loc.speed, 12.34, accuracy: 0.01)
        XCTAssertEqual(loc.bearing, 275.0, accuracy: 0.01)
        XCTAssertEqual(loc.accuracy, 8.5, accuracy: 0.01)
    }

    // MARK: - Edge Cases

    func testAccuracyClampedToMax() {
        // Accuracy > 655.35m should clamp to 65535 (UInt16 max)
        let loc = LocationTelemetry(
            latitude: 0, longitude: 0, altitude: 0,
            speed: 0, bearing: 0, accuracy: 999.0, lastUpdate: 0
        )
        let array = loc.toSensorArray()
        let decoded = LocationTelemetry.fromSensorArray(array)

        XCTAssertNotNil(decoded)
        XCTAssertEqual(decoded!.accuracy, 655.35, accuracy: 0.01,
                       "Accuracy should be clamped to UInt16 max (655.35m)")
    }

    func testInvalidArrayTooShort() {
        let shortArray: [LXMFMessagePackValue] = [.binary(Data(count: 4))]
        let result = LocationTelemetry.fromSensorArray(shortArray)
        XCTAssertNil(result, "Should reject arrays with fewer than 7 elements")
    }

    func testInvalidBinaryLength() {
        // lat data should be 4 bytes, not 2
        let badArray: [LXMFMessagePackValue] = [
            .binary(Data(count: 2)),  // Wrong size for lat
            .binary(Data(count: 4)),
            .binary(Data(count: 4)),
            .binary(Data(count: 4)),
            .binary(Data(count: 4)),
            .binary(Data(count: 2)),
            .int(0)
        ]
        let result = LocationTelemetry.fromSensorArray(badArray)
        XCTAssertNil(result, "Should reject arrays with wrong binary sizes")
    }

    func testDecodeGarbageDataReturnsNil() {
        let garbage = Data([0xFF, 0xFE, 0xFD, 0xFC])
        let result = TelemetryPacket.decode(from: garbage)
        XCTAssertNil(result, "Should return nil for non-msgpack data")
    }

    func testFieldConstants() {
        XCTAssertEqual(LXMessage.FIELD_TELEMETRY, 0x02)
        XCTAssertEqual(LXMessage.FIELD_TELEMETRY_STREAM, 0x03)
        XCTAssertEqual(LXMessage.FIELD_COMMANDS, 0x09)
    }
}

// Uses Data(hexString:) from LXMessageTests.swift
